# -*- coding: utf-8 -*-
"""Max and Min.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbF6iulQrtM0CCVVW3cagx0EZpon__sD
"""

score = input().split()
scorelist = list(map(int,score))
print(max(scorelist))
print(min(scorelist))