# -*- coding: utf-8 -*-
"""CountingFail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPI2ke0Baxg1TH2dsqE7HD8aYixM1dGx
"""

score = input().split()
scorelist = list(map(int,score))
sum = 0
for i in scorelist:
  if i<60:
    sum+=1
print(sum)